name: subiquity
version: git
summary: Ubuntu installer
description: The Ubuntu server installer
confinement: classic

apps:
  subiquity:
    command: usr/bin/subiquity
  console-conf:
    command: usr/bin/console-conf
  probert:
    command: bin/probert

parts:
  subiquity:
    plugin: python
    build-packages: [python-setuptools, pkg-config, lsb-release]
    stage-packages: [curtin, lsb-release]
    python-packages:
      - urwid
      - pyyaml
      - pyudev
      - attrs
      - systemd-python
    source: .
    source-type: git
  wrappers:
    plugin: dump
    source: .
    source-type: git
    organize:
      'bin/console-conf-tui': usr/bin/console-conf
      'bin/subiquity-tui': usr/bin/subiquity
      'bin/curtin-journald-forwarder': usr/bin/curtin-journald-forwarder
    prime:
      - usr/bin
  probert:
    plugin: python
    build-packages: [python-setuptools, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    source: https://github.com/CanonicalLtd/probert.git
    source-type: git
