name: subiquity
base: core18
version: git
summary: Ubuntu installer
description: The Ubuntu server installer
confinement: classic

apps:
  subiquity:
    command: usr/bin/subiquity
  subiquity-loadkeys:
    command: usr/bin/subiquity-loadkeys
  subiquity-configure-apt:
    command: usr/bin/subiquity-configure-apt
  subiquity-configure-run:
    command: usr/bin/subiquity-configure-run
  console-conf:
    command: usr/bin/console-conf
  probert:
    command: bin/probert
  subiquity-service:
    command: usr/bin/subiquity-service
    daemon: simple
    restart-condition: always

parts:
  curtin:
    plugin: python
    source-type: git
    source: git://git.launchpad.net/curtin
    source-commit: e967eebc3a427cd62f12f66473ea8430889bc206
    requirements: [requirements.txt]
    organize:
      'lib/python*/site-packages/usr/lib/curtin': 'usr/lib/'
    stage:
     - "*"
     - "-lib/python*/site-packages/_yaml.*.so"
     - "-lib/python*/site-packages/jsonschema"
  apport:
    plugin: python
    source-type: bzr
    source: lp:~ubuntu-core-dev/ubuntu/focal/apport/ubuntu
    build-packages:
      - python3-distutils-extra
      - python3-apt
      - python3-httplib2
      - python3-problem-report
      - python3-requests-unixsocket
    stage-packages:
      - python3-distutils-extra
      - python3-apt
      - python3-httplib2
      - python3-problem-report
      - python3-requests-unixsocket
    stage:
      - "lib/python*/site-packages/"
      - "-lib/python*/site-packages/etc/*"
      - "-lib/python*/site-packages/lib/*"
      - "share/apport/general-hooks/"
      - "usr/"
  subiquity:
    plugin: python
    build-packages:
      - libsystemd-dev
      - lsb-release
      - pkg-config
      - python3-distutils-extra
      - python3-urwid
    stage-packages:
      - cloud-init
      - libsystemd0
      - iso-codes
      - lsb-release
      - python3-bson
      - python3-distutils-extra
      - python3-urwid
      - python3-requests
      - python3-requests-unixsocket
      - ssh-import-id
    python-packages:
      - attrs
      - pyyaml
      - systemd-python
      #- urwid
    source: .
    source-type: git
    organize:
      'bin/console-conf-tui': usr/bin/console-conf
      'bin/subiquity-tui': usr/bin/subiquity
      'bin/subiquity-loadkeys': usr/bin/subiquity-loadkeys
      'bin/subiquity-service': usr/bin/subiquity-service
      'bin/subiquity-configure-apt': usr/bin/subiquity-configure-apt
      'bin/subiquity-configure-run': usr/bin/subiquity-configure-run
  users-and-groups:
    plugin: nil
    build-packages:
      - user-setup
    override-build: |
      echo "get passwd/user-default-groups" | \
        debconf-communicate user-setup | \
        cut -d ' ' -f 2- > $SNAPCRAFT_PART_INSTALL/users-and-groups
      cp /usr/lib/user-setup/reserved-usernames $SNAPCRAFT_PART_INSTALL/
    stage:
      - users-and-groups
      - reserved-usernames
  kbdnames:
    plugin: nil
    build-packages:
      - console-setup
      - locales
      - xkb-data-i18n
    override-build: |
      /usr/share/console-setup/kbdnames-maker /usr/share/console-setup/KeyboardNames.pl > $SNAPCRAFT_PART_INSTALL/kbdnames.txt
    stage:
      - kbdnames.txt
  font:
    plugin: dump
    source: ./
    organize:
      font/subiquity.psf: subiquity.psf
    stage:
      - subiquity.psf
  probert:
    plugin: python
    build-packages: [python-setuptools, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    stage-packages: [libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    source: https://github.com/CanonicalLtd/probert.git
    source-type: git
    source-commit: 4793e16ea1c397c44e115dc90eafa60df0947d5c
    requirements: [requirements.txt]
